---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: bandwidth-chaos
  namespace: default
spec:
  appinfo:
    appns: ''
    applabel: ''
    appkind: ''
  engineState: 'active'
  chaosServiceAccount: bandwidth-attenuation-sa
  annotationCheck: 'false'
  experiments:
    - name: bandwidth-attenuation
      spec:
        components:
          env:
            # in seconds
            - name: TOTAL_CHAOS_DURATION
              value: '30'

            # in kbps
            - name: BANDWIDTH_RATE
              value: '750kbit'

            - name: BUFFER_SIZE
              value: '10kb'

            - name: LIMIT
              value: '20mb'

            - name: SERVICE_NAME
              value: 'tocl1-to-cbc2-mirrormaker2'

            - name: NAMESPACE
              value: 'default'
