---
apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Attenuates bandwidth between two pods by applying traffic control (tc) rules.
kind: ChaosExperiment
metadata:
  name: pod-bw-attenuation
  labels:
    name: pod-bw-attenuation
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: ci
spec:
  definition:
    scope: Namespaced
    permissions:
      # Create and monitor the experiment & helper pods
      - apiGroups: [""]
        resources: ["pods"]
        verbs:
          [
            "create",
            "delete",
            "get",
            "list",
            "patch",
            "update",
            "deletecollection",
          ]
      # Performs CRUD operations on the events inside chaosengine and chaosresult
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create", "get", "list", "patch", "update"]
      # Track and get the runner, experiment, and helper pods log
      - apiGroups: [""]
        resources: ["pods/log"]
        verbs: ["get", "list", "watch"]
      # for creating and managing to execute commands inside target container
      - apiGroups: [""]
        resources: ["pods/exec"]
        verbs: ["get", "list", "create"]
      # for configuring and monitor the experiment job by the chaos-runner pod
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["create", "list", "get", "delete", "deletecollection"]
      # for creation, status polling and deletion of litmus chaos resources used within a chaos workflow
      - apiGroups: ["litmuschaos.io"]
        resources: ["chaosengines", "chaosexperiments", "chaosresults"]
        verbs: ["create", "list", "get", "patch", "update", "delete"]
    image: "litmuschaos.docker.scarf.sh/litmuschaos/go-runner:3.0.0"
    imagePullPolicy: Always
    args:
      - -c
      - |
        #!/bin/bash
        echo "Starting bandwidth attenuation chaos experiment"

        SOURCE_POD=$(kubectl get pod -l ${SOURCE_LABEL} -n ${NAMESPACE} -o jsonpath='{.items[0].metadata.name}')
        DESTINATION_POD=$(kubectl get pod -l ${DESTINATION_LABEL} -n ${NAMESPACE} -o jsonpath='{.items[0].metadata.name}')

        # Create a helper pod to apply traffic control rules
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: Pod
        metadata:
          name: tc-helper
          namespace: ${NAMESPACE}
          labels:
            app: tc-helper
        spec:
          containers:
          - name: tc-helper
            image: busybox
            command:
            - /bin/sh
            - -c
            - |
              echo "Applying bandwidth attenuation using tc"

              SOURCE_IP=$(kubectl get pod ${SOURCE_POD} -n ${NAMESPACE} -o jsonpath='{.status.podIP}')
              DESTINATION_IP=$(kubectl get pod ${DESTINATION_POD} -n ${NAMESPACE} -o jsonpath='{.status.podIP}')

              tc qdisc add dev eth0 root handle 1: htb default 11
              tc class add dev eth0 parent 1: classid 1:1 htb rate ${BANDWIDTH_RATE}
              tc filter add dev eth0 protocol ip parent 1:0 prio 1 u32 match ip dst ${DESTINATION_IP} flowid 1:1
              
              sleep ${TOTAL_CHAOS_DURATION}

              echo "Removing bandwidth attenuation"
              tc qdisc del dev eth0 root
              echo "Bandwidth attenuation completed"
            securityContext:
              privileged: true
          restartPolicy: Never
        EOF

        sleep ${TOTAL_CHAOS_DURATION}

        kubectl delete pod tc-helper -n ${NAMESPACE}

        echo "Chaos experiment completed"
    command:
      - /bin/bash
    env:
      - name: TOTAL_CHAOS_DURATION
        value: "15"

      - name: BANDWIDTH_RATE
        value: "750kbit"

      - name: BUFFER_SIZE
        value: "10kb"

      - name: LIMIT
        value: "20mb"

      - name: SOURCE_LABEL
        value: "app.kubernetes.io/instance=source-app"

      - name: DESTINATION_LABEL
        value: "app.kubernetes.io/instance=destination-app"

      - name: NAMESPACE
        value: "default"

    labels:
      name: pod-bw-attenuation
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: 3.0.0
